version: '3'
services:
  carnivorous-garden:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5005:5005
    volumes:
      - ./logs:/app/logs/
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318
  
  alloy:
    build:
      context: .
      dockerfile: Dockerfile.alloy
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    env_file:
      - .env